# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex Cameron | Astronomer
email: alex.cameron@physics.ox.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Alex James Cameron. Astronomer / astrophysicist at the University
  of Oxford. PhD from the University of Melbourne. Interests:
  extragalactic astronomy, galaxy evolution, chemical evolution of galaxies,
  baryon cycle, JWST, high-redshift galaxies
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://alexjcameron.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  AlexJCameron

# Build settings
theme: bay_jekyll_theme
plugins:
  - jekyll-feed

header:
  pages:
    # - name: Blog  # <-- blog.md
    - name: Research  # <-- blog.md
      slug: /research
    - name: Media & Outreach
      slug: /outreach
    - name: Publications  # <-- blog.md
    - name: CV  # <-- blog.md
    # - name: Whatever  # <-- whatever.md


footer:
  show_powered_by: false
  contact:
    - name: Email
      value: alex.cameron at physics.ox.ac.uk
      link: mailto:alex.cameron@physics.ox.ac.uk
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  # follow:
  #   - name: Twitter
  #     link: http://twitter.com/YourTwitterUsername
  #     username: "@YourTwitterUsername"
  #   - name: Facebook
  #     link: http://facebook.com/YourFacebookUsername
  #   - name: LinkedIn
  #     link: http://linkedin.com/in/YourLinkedInUsername
  #   - name: GitHub
  #     link: http://github.com/YourGitHubUsername
  #   - name: Dribbble
  #     link: https://dribbble.com/YourDribbbleUsername
  #   - name: Weibo
  #     link: http://weibo.com/u/YourWeiboUsername
  #   - name: RSS
  #     link: /feed.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
